export enum EnvConfigEnum {
  PORT = 'PORT',
  TOKEN_SECRET = 'TOKEN_SECRET',
  REFRESH_TOKEN_SECRET = 'REFRESH_TOKEN_SECRET',
  TOKEN_EXPIRE_IN = 'TOKEN_EXPIRE_IN',
  REDIS_HOST = 'REDIS_HOST',
  MONGODB_URL = 'MONGODB_URL',
}
